[phases.setup]
nixPkgs = ["nodejs_18", "python311", "ffmpeg"]

[phases.install]
cmds = [
  "ln -s $(which python3) /usr/bin/python || true",
  "python --version",
  "npm install"
]

[phases.start]
cmd = "node server.js"
